

CREATE TABLE IF NOT EXISTS staging.customers (
    customer_id text PRIMARY KEY,
    customer_unique_id text NOT NULL,
    customer_zip_code_prefix text NOT NULL,
    customer_city text NOT NULL,
    customer_state text NOT NULL
);

CREATE TABLE IF NOT EXISTS staging.products (
    product_id text PRIMARY KEY,
    product_category_name text,
    product_name_lenght integer,
    product_description_lenght integer,
    product_photos_qty integer,
    product_weight_g integer,
    product_length_cm integer,
    product_height_cm integer,
    product_width_cm integer
);

CREATE TABLE IF NOT EXISTS staging.sellers (
    seller_id text PRIMARY KEY,
    seller_zip_code_prefix text NOT NULL,
    seller_city text NOT NULL,
    seller_state text NOT NULL
);

CREATE TABLE IF NOT EXISTS staging.category_translation (
    product_category_name text PRIMARY KEY,
    product_category_name_english text NOT NULL
);

CREATE TABLE IF NOT EXISTS staging.orders (
    order_id text PRIMARY KEY,
    customer_id text NOT NULL REFERENCES staging.customers (customer_id),
    order_status text NOT NULL,
    order_purchase_timestamp timestamp NOT NULL,
    order_approved_at timestamp,
    order_delivered_carrier_date timestamp,
    order_delivered_customer_date timestamp,
    order_estimated_delivery_date timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS staging.order_items (
    order_id text NOT NULL REFERENCES staging.orders (order_id),
    order_item_id integer NOT NULL,
    product_id text NOT NULL REFERENCES staging.products (product_id),
    seller_id text NOT NULL REFERENCES staging.sellers (seller_id),
    shipping_limit_date timestamp NOT NULL,
    price numeric(12, 2) NOT NULL,
    freight_value numeric(12, 2) NOT NULL,
    PRIMARY KEY (order_id, order_item_id)
);

CREATE TABLE IF NOT EXISTS staging.order_payments (
    order_id text NOT NULL REFERENCES staging.orders (order_id),
    payment_sequential integer NOT NULL,
    payment_type text NOT NULL,
    payment_installments integer NOT NULL,
    payment_value numeric(12, 2) NOT NULL,
    PRIMARY KEY (order_id, payment_sequential)
);

CREATE TABLE IF NOT EXISTS staging.order_reviews (
    review_id text NOT NULL,
    order_id text NOT NULL REFERENCES staging.orders (order_id),
    review_score smallint NOT NULL,
    review_comment_title text,
    review_comment_message text,
    review_creation_date timestamp NOT NULL,
    review_answer_timestamp timestamp NOT NULL,
    PRIMARY KEY (review_id, order_id)
);

CREATE TABLE IF NOT EXISTS staging.geolocation_observations (
    geolocation_observation_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    geolocation_zip_code_prefix text NOT NULL,
    geolocation_lat numeric(22, 20) NOT NULL,
    geolocation_lng numeric(19, 16) NOT NULL,
    geolocation_city text NOT NULL,
    geolocation_state text NOT NULL
);
